name: Inciteful-Docs-CI

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-site:
    runs-on: ubuntu-16.04
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: GCloud Setup
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCLOUD_ACCOUNT_KEY }}
        export_default_credentials: true
    - name: Setup Cache
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Build Jekyll
      uses:  lemonarc/jekyll-action@1.0.0
    - name: Upload Artifacts to GCloud
      run: |
        gsutil rsync -d -r ./_site/ gs://inciteful-docs/